In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
os.chdir("D:\Stroke-Prediction")

In [3]:
os.listdir()

['healthcare-dataset-stroke-data.csv',
 'lightgrey.jpg',
 'model.pkl',
 'Stroke-cleaned-preprocessed-data.csv',
 'template']

In [4]:
dataset = pd.read_csv("Stroke-cleaned-preprocessed-data.csv")

In [5]:
dataset.head()

id  gender  age  hypertension  heart_disease  ever_married  work_type  \
0  24905       0   65             0              0             1          0   
1  24669       0   77             0              1             1          0   
2  60739       0   79             1              1             0          1   
3  71279       0   71             0              0             1          2   
4  10434       0   69             0              0             0          0   

   Residence_type  avg_glucose_level   bmi  smoking_status  stroke  
0               0             205.77  46.0               1       1  
1               1             231.56  36.9               2       1  
2               1              60.94  28.9               2       1  
3               0             263.32  38.7               2       1  
4               0              94.39  22.8               2       1

In [6]:
dataset.tail()

id  gender  age  hypertension  heart_disease  ever_married  \
9717  18234       0   80             1              0             1   
9718  44873       0   81             0              0             1   
9719  19723       0   35             0              0             1   
9720  37544       1   51             0              0             1   
9721  44679       0   44             0              0             1   

      work_type  Residence_type  avg_glucose_level   bmi  smoking_status  \
9717          0               0              83.75  28.9               2   
9718          1               0             125.20  40.0               2   
9719          1               1              82.99  30.6               2   
9720          0               1             166.29  25.6               1   
9721          2               0              85.28  26.2               3   

      stroke  
9717       0  
9718       0  
9719       0  
9720       0  
9721       0

In [7]:
x = dataset.iloc[:,[2,3,4,5,6,8,9,10]].values
y = dataset.iloc[:,-1].values

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [10]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
classifier = RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)

In [12]:
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [13]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [1 1]
 [1 1]]


In [14]:
from sklearn.metrics import confusion_matrix

In [15]:
cm = confusion_matrix(y_test,y_pred)

In [16]:
print(cm)

[[951  18]
 [  0 976]]


In [17]:
from sklearn.metrics import accuracy_score

In [18]:
accuracy_score(y_test,y_pred)

0.990745501285347

In [19]:
import pickle

In [20]:
pickle.dump(classifier,open('model.pkl','wb'))

In [21]:
model = pickle.load(open('model.pkl','rb'))

In [22]:
print(model.predict([[71,0,0,1,2,263.32,38.7,2]]))

[1]


In [23]:
print(model.predict([[80,1,0,1,0,83.75,28.9,2]]))

[0]


In [24]:
y_pred_train = classifier.predict(x_train)
accuracy_score(y_train,y_pred_train)

0.9997428314259997

In [25]:
cm = confusion_matrix(y_train,y_pred_train)

In [26]:
print(cm)

[[3890    2]
 [   0 3885]]
